site_name: Continuum Knowledge Base
site_description: Strategies, Playbooks, Ops, and Research
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - toc.integrate
nav:
  - Home: index.md
  - Strategies:
    - Overview: strategies/index.md
    - Super-Squeeze+: strategies/super-squeeze.md
    - Scalping Modules: strategies/scalping.md
    - Orchestrator: strategies/orchestrator.md
    - Backtesting: strategies/backtesting.md
    - Risk Management: strategies/risk.md
  - Playbooks:
    - Operator Auto-Execution: playbooks/operator.md
    - IBKR Checklist: playbooks/ibkr-checklist.md
    - Deployment: playbooks/deployment.md
    - Debugging: playbooks/debugging.md
    - SEAL Team Ops: playbooks/seal-team.md
  - Ops:
    - Deploy Status: ops/deploy-status.md
    - Secrets & Env: ops/secrets.md
    - Monitoring: ops/monitoring.md
    - Roadmaps: ops/roadmaps.md
  - Data:
    - Feeds & Adapters: data/feeds.md
    - Data Lake: data/lake.md
    - Scraping Pipelines: data/scraping.md
    - Research Datasets: data/research-datasets.md
  - Research:
    - GME: research/gme.md
    - BBBY Bonds: research/bbby-2044.md
    - Macro: research/macro.md
    - ETF Complex: research/etf-complex.md
    - Catalysts: research/catalysts.md
  - Appendix:
    - Glossary: appendix/glossary.md
    - Abbreviations: appendix/abbreviations.md
    - Tools: appendix/tools.md
    - References: appendix/refs.md
